### PR TITLE
Broadly overhaul forwarder generation and update to 14.34.31931

### LINKED ISSUE #11: Consider linking with /NOENTRY option
As these DLLs have no code on their own, I think the standard CRT initialization and termination routines aren't needed. The gains on performance and file size will be negligible but I believe this project configuration change may keep things tidier. For example, the api-ms-win-crt-*.dll libraries from the Universal CRT (for Windows versions before Windows 10) are pure forwarders to Ucrtbase.dll and they haven't an entry point.

There is a dllmain.cpp file at *140_release\vcrt_fwd_x64_release\msvcp140_app*, but it isn't even referenced by any project file.

### LINKED ISSUE #35: No PDBs included for the DLLs
This makes it impossible to run binskim over them, which is a requirement to use nugets in various Microsoft corp repos. I think if instead /noentry was used (to remove all the code from them) that might be sufficient instead of publishing the PDBs. The PDBs are also not on either Microsoft symbol server.

### LINKED ISSUE #41: All libraries in this repo should have VERSIONINFO resources
Some deployment technologies use file version checks to determine whether they need to update files on disk. Since these are in fact DLLs that get shipped alongside applications that _may be deploying outside of MSIX,_ they should have version resources.

### Proposal

Each DLL produced via this project's build system contains a VERSIONINFO resource that mirrors the VERSIONINFO resource of the specific version of the specific DLL it is pretending to be.

### PR DESCRIPTION
**Pull request by DHowett**
Hey all,
We use the Forwarders pretty heavily on the Terminal project.
To better support our needs and the needs of our community we've made the following changes:

1. Added a version resource to every forwarder file, automatically generated by the python script
2. Updated the forwarders to runtime version 14.34
3. Disabled the generation of an entrypoint in each DLL
4. Added a forwarder for `msvcrt140_atomic_wait`, which is part of the updated runtime
5. Updated all projects to toolset v143 and SDK 22621 to ensure that they still build

To that end, and to improve project consistency, I've made the Python script generate new project files every time it is run.
That will make it easier to address things like #36.

Closes #41 
Closes #35 
Closes #11

### CODE REVIEW

**Comment by DHowett** [comment]
The pull request is broken down into individual commits, which are going to be easier to review than the full PR

**Comment by awakecoding** [comment]
Hi! I'd just like to chime in and say that this is a quite an important improvement which we would need for our own Devolutions Windows Terminal distribution. The lack of version info makes repackaging more difficult since our installer normally upgrades files for which the version info has changed, unless told to always overwrite the files (less efficient).

https://github.com/devolutions/wt-distro
https://twitter.com/awakecoding/status/1600975145488687105

Whoever is in charge of this project, I would really appreciate if this could be merged and a new release done after to get code versioned, code signed executables :)

**Comment by DHowett** [comment]
Hey @manodasanW, would you mind having a look at this pull request? I'd love to get it off my to-do list and onto my to-done list 😄

**Review by manodasanW — APPROVED** [review]
Thanks @DHowett for these changes.  The changes look good and I tested them with our samples which all continue to work.

**Pull request merged**
